altruist:
  server:
    host: "0.0.0.0"
    port: 5000

  transport:
    mode: "websocket"

  game:
    engine:
      dimension: "3D"
      framerateHz: 30
      unit: "Seconds"
      gravity:
        x: 0
        y: -9.81

    worlds:
      partitioner:
        width: 64
        height: 64
        depth: 64
      items:
        - index: 0
          size:
            x: 100
            y: 100
          gravity:
            x: 0
            y: 0
          position:
            x: 0
            y: 0
