altruist:
  server:
    http:
      host: "0.0.0.0"
      port: 8081
      path: "/"
    transport:
      mode: websocket
      codec:
        provider: messagepack

  persistence:
    cache:
      provider: inmemory
