altruist:
  environment:
    mode: "3D"

  server:
    http:
      host: "0.0.0.0"
      port: 8080
      path: "/"
    transport:
      mode: tcp
      timeout: 300
      codec:
        provider: messagepack
      config:
        port: 13000

  persistence:
    cache:
      provider: inmemory

  game:
    engine:
      diagnostics: true
      frequency: 25
      unit: "hz"

    visibility:
      range: 5000

    physics:
      enabled: false

    worlds:
      partitioner: { width: 256, height: 256, depth: 256 }
      items:
        - index: 0
          id: "arena"
          size: { x: 10000, y: 10000, z: 1000 }
          gravity: { x: 0, y: -9.81, z: 0 }
