name: .NET

permissions:
  pull-requests: write
  contents: read

on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main", "staging" ]

jobs:
  validate_version:
    runs-on: ubuntu-latest
    if: |
      (
        github.event_name == 'push' &&
        github.ref == 'refs/heads/main' &&
        !startsWith(github.head_ref, 'release/')
      )
      ||
      (
        github.event_name == 'pull_request' &&
        github.base_ref == 'main' &&
        !startsWith(github.head_ref, 'release/')
      )
    steps:
    - uses: actions/checkout@v4

    - name: Install dos2unix
      run: sudo apt-get install dos2unix

    - name: Validate Project Versions
      run: |
        echo ${{ github.head_ref }}
        echo "📦 Checking versions..."
        dos2unix ./Altruist/validate_versions.sh
        chmod +x ./Altruist/validate_versions.sh
        ./Altruist/validate_versions.sh

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Setup .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore ./Tests/Tests.csproj

    # Build the Tests project
    - name: Build Tests project
      run: dotnet build ./Tests/Tests.csproj --no-restore

    # Run Tests
    - name: Run Tests
      run: dotnet test ./Tests/Tests.csproj --no-build --verbosity normal

    # 📦 Pack the Altruist solution for NuGet (only on push to main)
    - name: Pack NuGet packages
      run: dotnet pack ./Altruist --configuration Release --output ./Altruist/nupkgs

  update-version:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.set-version.outputs.VERSION }}
      RELEASE_BRANCH: ${{ steps.set-version.outputs.RELEASE_BRANCH }}
    needs: [build, validate_version]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Versions
        id: set-version
        run: |
          VERSION="v$(date +'%Y.%m.%d')-$(git rev-parse --short HEAD)"
          RELEASE_BRANCH="release/$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "RELEASE_BRANCH=$RELEASE_BRANCH" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "RELEASE_BRANCH=$RELEASE_BRANCH" >> $GITHUB_OUTPUT
          
      - name: Clone repository using PAT
        run: |
          echo "Cloning repo and checking out release branch: ${{ env.RELEASE_BRANCH }}"
          git clone https://x-access-token:${{ secrets.ACTION_PAT }}@github.com/Vulcaine/Altruist.git repo
          cd repo
          git config user.name "Vulcaine"
          git config user.email "Vulcaine@users.noreply.github.com"
          git fetch && git checkout main && git rebase
          git checkout -b "${{ env.RELEASE_BRANCH }}"
          
      - name: Install dos2unix
        run: sudo apt-get install dos2unix

      - name: Update Project Versions
        working-directory: ./repo
        run: |
          echo "📦 Updating project versions to match version.txt..."
          dos2unix ./Altruist/update_versions.sh
          chmod +x ./Altruist/update_versions.sh
          ./Altruist/update_versions.sh

      - name: Commit and Push Changes
        working-directory: ./repo
        run: |
          git add .
          git commit -m "chore: update package versions to match version.txt" || echo "No changes to commit"
          git push --set-upstream origin "${{ env.RELEASE_BRANCH }}" || echo "Branch is up to date"

  release:
    runs-on: ubuntu-latest
    needs: update-version
    steps:
    # Checkout main
    - name: Checkout repository
      uses: actions/checkout@v4

    # Setup .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Clone repository using PAT
      run: |
        git clone https://x-access-token:${{ secrets.ACTION_PAT }}@github.com/Vulcaine/Altruist.git repo
        cd repo
        git config user.name "Vulcaine"
        git config user.email "Vulcaine@users.noreply.github.com"
        git fetch
        git checkout "${{ needs.update-version.outputs.RELEASE_BRANCH }}"

    # Build the package using dotnet pack
    - name: Build Package
      working-directory: ./repo
      run: dotnet pack ./Altruist --configuration Release --output ./Altruist/nupkgs

    # Create a new version tag based on the release branch
    - name: Create Tag on Release Branch
      working-directory: ./repo
      run: |
        git tag "${{ needs.update-version.outputs.VERSION }}"
        git push origin "${{ needs.update-version.outputs.VERSION }}"

    - name: Create GitHub Release manually and upload artifacts
      working-directory: ./repo
      env:
        VERSION: ${{ needs.update-version.outputs.VERSION }}
        GH_PAT: ${{ secrets.ACTION_PAT }}
      run: |
        echo "📦 Creating GitHub release for tag $VERSION"
    
        # Create release and capture response
        API_RESPONSE=$(curl -s -X POST "https://api.github.com/repos/Vulcaine/Altruist/releases" \
          -H "Authorization: token $GH_PAT" \
          -H "Accept: application/vnd.github+json" \
          -d "$(jq -n \
            --arg tag "$VERSION" \
            --arg name "$VERSION" \
            --arg body "Automated release for $VERSION" \
            '{ tag_name: $tag, name: $name, body: $body, draft: false, prerelease: false }')")
    
        echo "✅ GitHub release created."
    
        # Extract upload URL from response
        UPLOAD_URL=$(echo "$API_RESPONSE" | jq -r '.upload_url' | sed 's/{?name,label}//')
    
        echo "📤 Uploading artifacts to: $UPLOAD_URL"
    
        for file in ./Altruist/nupkgs/*.nupkg; do
          FILENAME=$(basename "$file")
          echo "📤 Uploading $FILENAME"
          curl -s --data-binary @"$file" \
            -H "Authorization: token $GH_PAT" \
            -H "Content-Type: application/octet-stream" \
            "$UPLOAD_URL?name=$FILENAME"
        done
    
        echo "✅ Done uploading release artifacts."

    # Publish the package to NuGet
    - name: Publish to NuGet
      working-directory: ./repo
      env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: |
        dotnet nuget push ./Altruist/nupkgs/*.nupkg -k "$NUGET_API_KEY" -s https://api.nuget.org/v3/index.json --skip-duplicate

    - name: Create Release Pull Request Via GitHub API
      working-directory: ./repo
      run: |
        echo "📬 Creating pull request via GitHub API..."
        curl -s -X POST https://api.github.com/repos/Vulcaine/Altruist/pulls \
          -H "Authorization: token ${{ secrets.ACTION_PAT }}" \
          -H "Accept: application/vnd.github+json" \
          -d '{
            "title": "${{ needs.update-version.outputs.RELEASE_BRANCH }}: Merge Release into Main",
            "body": "This PR merges the new release version back to main",
            "head": "${{ needs.update-version.outputs.RELEASE_BRANCH }}",
            "base": "main"
          }'
