name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Setup .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore ./Tests/Tests.csproj

    # Build the Tests project
    - name: Build Tests project
      run: dotnet build ./Tests/Tests.csproj --no-restore

    # Run Tests
    - name: Run Tests
      run: dotnet test ./Tests/Tests.csproj --no-build --verbosity normal

  version-check:
    runs-on: ubuntu-latest
    needs: build
    # Runs only on push to main branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Validate Project Versions
        run: |
          echo "📦 Checking versions..."
          chmod +x ./validate-version.sh
          ./validate-version.sh

  release:
    runs-on: ubuntu-latest
    needs: version-check
    # Runs only on push to main branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4

    # Setup .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # Create a new version tag based on the commit hash
    - name: Create Tag
      run: |
        VERSION="v$(date +'%Y.%m.%d')-$(git rev-parse --short HEAD)"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        git tag "$VERSION"
        git push origin "$VERSION"

    # Build the package using dotnet pack
    - name: Build Package
      run: dotnet pack ./Altruist --configuration Release --output ./Altruist/nupkgs

    # Publish the package to NuGet
    - name: Publish to NuGet
      env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: |
        dotnet nuget push ./Altruist/nupkgs/*.nupkg -k "$NUGET_API_KEY" -s https://api.nuget.org/v3/index.json --skip-duplicate

    # Create a new GitHub release using the tag created
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.VERSION }}
        files: ./Altruist/nupkgs/*.nupkg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
